name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download file
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: ./artifacts
      - name: test
        run: ls
      - name: test-artifact
        run: |
          cd artifacts
          ls      
      - name: display hello
        run: cat ./artifacts/hello.txt 
